name: Express Deployment

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd BEforMarko/
          git fetch origin
          git checkout production
          git pull
          docker build -t markobe .
          docker stop markobe-container || true
          docker rm marko-container || true
          docker run -d --name marko-container -p 7021:7021 markobe
            