name: Express Deployment

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Kiểm tra giá trị SSH_PRIVATE_KEY
      - name: Debug SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}"
      
      # Các bước deploy khác
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd BEforMarko/
            git fetch origin
            git checkout production
            git pull
            docker build -t markobe .
            docker stop markobe-container || true
            docker rm markobe-container || true
            docker run -d --name markobe-container -p 7021:7021 markobe
